// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Output struct {
	Input string `json:"input"`
}

type OutputNillable struct {
	Input *string `json:"input,omitempty"`
}

type Query struct {
}
