// Code generated by github.com/loa/graphqlclientgen, DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/loa/graphqlclientgen"
)

type (
	// Client for graphqlclient
	Client struct {
		protoClient graphqlclientgen.ProtoClient
	}

	// NewTodo
	NewTodo struct {
		// Text todo text
		Text string `json:"text"`
		// UserId user to assign todo
		UserId string `json:"userId"`
	}

	// Todo entry with text and done status
	Todo struct {
		// Done status of todo
		Done bool `json:"done"`
		// ID primary id of todo
		ID string `json:"id"`
		// Text todo text
		Text string `json:"text"`
		// User assigned to todo
		User *User `json:"user"`
	}

	// User with name and assigned todos
	User struct {
		// ID primary id of user
		ID string `json:"id"`
		// Name of user
		Name string `json:"name"`
		// Todos all todos assigned to user
		Todos *Todo `json:"todos"`
	}

	TodoFieldScalar string
	TodoField       interface {
		TodoFieldGraphQL() string
	}
	TodoFields []TodoField

	UserFieldScalar string
	UserField       interface {
		UserFieldGraphQL() string
	}
	UserFields []UserField
)

var (
	TodoFieldDone TodoFieldScalar = "done"
	TodoFieldID   TodoFieldScalar = "id"
	TodoFieldText TodoFieldScalar = "text"
	UserFieldID   UserFieldScalar = "id"
	UserFieldName UserFieldScalar = "name"
)

func (field TodoFieldScalar) TodoFieldGraphQL() string {
	return string(field)
}

func (field UserFieldScalar) UserFieldGraphQL() string {
	return string(field)
}

func (fields UserFields) TodoFieldGraphQL() string {
	var s []string
	for _, field := range fields {
		s = append(s, field.UserFieldGraphQL())
	}
	return fmt.Sprintf("user { %s }", strings.Join(s, ", "))
}

func (fields TodoFields) UserFieldGraphQL() string {
	var s []string
	for _, field := range fields {
		s = append(s, field.TodoFieldGraphQL())
	}
	return fmt.Sprintf("todos { %s }", strings.Join(s, ", "))
}

// New create new graphqlclient
func New(protoClient graphqlclientgen.ProtoClient) Client {
	return Client{
		protoClient: protoClient,
	}
}

// CreateTodo (mutation) create a new todo
func (client Client) CreateTodo(
	ctx context.Context,
	input NewTodo,
	fields TodoFields,
) (Todo, error) {
	var s []string
	for _, field := range fields {
		s = append(s, field.TodoFieldGraphQL())
	}
	fieldsContent := strings.Join(s, ",")

	body := graphqlclientgen.Body{
		Query: fmt.Sprintf(`
        mutation ($input: NewTodo!) {
            createTodo (input: $input) { %s }
        }`, fieldsContent),
		Variables: map[string]any{
			"input": input,
		},
	}

	var res graphqlclientgen.Response
	if err := client.protoClient.Do(ctx, body, &res); err != nil {
		return Todo{}, err
	}

	var data struct {
		CreateTodo Todo `json:"createTodo"`
	}

	if len(res.Errors) > 0 {
		return data.CreateTodo, errors.New(res.Errors[0].Message)
	}

	if err := json.Unmarshal(res.Data, &data); err != nil {
		return data.CreateTodo, err
	}

	return data.CreateTodo, nil
}

// Todos (query) returns all todos
func (client Client) Todos(
	ctx context.Context,
	fields TodoFields,
) ([]Todo, error) {
	var s []string
	for _, field := range fields {
		s = append(s, field.TodoFieldGraphQL())
	}
	fieldsContent := strings.Join(s, ",")

	body := graphqlclientgen.Body{
		Query: fmt.Sprintf(`
        query {
            todos { %s }
        }`, fieldsContent),
		Variables: map[string]any{},
	}

	var res graphqlclientgen.Response
	if err := client.protoClient.Do(ctx, body, &res); err != nil {
		return nil, err
	}

	var data struct {
		Todos []Todo `json:"todos"`
	}

	if len(res.Errors) > 0 {
		return data.Todos, errors.New(res.Errors[0].Message)
	}

	if err := json.Unmarshal(res.Data, &data); err != nil {
		return data.Todos, err
	}

	return data.Todos, nil
}
