// Code generated by github.com/loa/graphqlclientgen, DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/loa/graphqlclientgen"
)

type (
	// Client for graphqlclient
	Client struct {
		protoClient graphqlclientgen.ProtoClient
	}

	// Todo entry with text and done status
	Todo struct {
		// Done status of todo
		Done bool `json:"done"`
		// ID primary id of todo
		ID string `json:"id"`
		// Text todo text
		Text string `json:"text"`
		// User assigned to todo
		User *User `json:"user"`
	}

	// User with name and assigned todos
	User struct {
		// ID primary id of user
		ID string `json:"id"`
		// Name of user
		Name string `json:"name"`
		// Todos all todos assigned to user
		Todos *Todo `json:"todos"`
	}
)

// New create new graphqlclient
func New(protoClient graphqlclientgen.ProtoClient) Client {
	return Client{
		protoClient: protoClient,
	}
}

// CreateTodo (mutation) create a new todo
func (client Client) CreateTodo(ctx context.Context) (Todo, error) {
	body := graphqlclientgen.Body{
		Query: "mutation { createTodo { id, text } }",
	}

	var res graphqlclientgen.Response
	if err := client.protoClient.Do(ctx, body, &res); err != nil {
		return Todo{}, err
	}

	var data struct {
		CreateTodo Todo `json:"createTodo"`
	}

	if len(res.Errors) > 0 {
		return data.CreateTodo, errors.New(res.Errors[0].Message)
	}

	if err := json.Unmarshal(res.Data, &data); err != nil {
		return data.CreateTodo, nil
	}

	return data.CreateTodo, nil
}

// Todos (query) returns all todos
func (client Client) Todos(ctx context.Context) ([]Todo, error) {
	body := graphqlclientgen.Body{
		Query: "query { todos { id, text } }",
	}

	var res graphqlclientgen.Response
	if err := client.protoClient.Do(ctx, body, &res); err != nil {
		return nil, err
	}

	var data struct {
		Todos []Todo `json:"todos"`
	}

	if len(res.Errors) > 0 {
		return data.Todos, errors.New(res.Errors[0].Message)
	}

	if err := json.Unmarshal(res.Data, &data); err != nil {
		return data.Todos, nil
	}

	return data.Todos, nil
}
