// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	// todo text
	Text string `json:"text"`
	// user to assign todo
	UserID string `json:"userId"`
}

type Query struct {
}

// Todo entry with text and done status
type Todo struct {
	// primary id of todo
	ID string `json:"id"`
	// todo text
	Text string `json:"text"`
	// done status of todo
	Done bool `json:"done"`
	// user assigned to todo
	User *User `json:"user"`
}

// User with name and assigned todos
type User struct {
	// primary id of user
	ID string `json:"id"`
	// name of user
	Name string `json:"name"`
	// all todos assigned to user
	Todos []*Todo `json:"todos"`
}
