// Code generated by github.com/loa/graphqlclientgen, DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/loa/graphqlclientgen"
)

type (
	// Client for graphqlclient
	Client struct {
		protoClient graphqlclientgen.ProtoClient
	}

	// NewTodo
	NewTodo struct {
		// Text todo text
		Text string `json:"text"`
		// User to assign todo
		User uuid.UUID `json:"user"`
	}

	// Todo entry with text and done status
	Todo struct {
		// Done status of todo
		Done bool `json:"done"`
		// ID primary id of todo
		ID string `json:"id"`
		// Text todo text
		Text string `json:"text"`
		// User assigned to todo
		User *User `json:"user"`
	}

	// User with name and assigned todos
	User struct {
		// ID primary id of user
		ID uuid.UUID `json:"id"`
		// Name of user
		Name string `json:"name"`
		// Todos all todos assigned to user
		Todos []*Todo `json:"todos"`
	}

	TodoFieldScalar string
	TodoField       interface {
		TodoFieldGraphQL() string
	}
	TodoFields    []TodoField
	TodoFieldUser []UserField

	UserFieldScalar string
	UserField       interface {
		UserFieldGraphQL() string
	}
	UserFields     []UserField
	UserFieldTodos []TodoField
)

var (
	TodoFieldDone TodoFieldScalar = "done"
	TodoFieldID   TodoFieldScalar = "id"
	TodoFieldText TodoFieldScalar = "text"
	UserFieldID   UserFieldScalar = "id"
	UserFieldName UserFieldScalar = "name"
)

func (field TodoFieldScalar) TodoFieldGraphQL() string {
	return string(field)
}

func (field UserFieldScalar) UserFieldGraphQL() string {
	return string(field)
}

func (fields TodoFieldUser) TodoFieldGraphQL() string {
	var s []string
	for _, field := range fields {
		s = append(s, field.UserFieldGraphQL())
	}
	return fmt.Sprintf("user { %s }", strings.Join(s, ", "))
}

func (fields UserFieldTodos) UserFieldGraphQL() string {
	var s []string
	for _, field := range fields {
		s = append(s, field.TodoFieldGraphQL())
	}
	return fmt.Sprintf("todos { %s }", strings.Join(s, ", "))
}

// New create new graphqlclient
func New(protoClient graphqlclientgen.ProtoClient) Client {
	return Client{
		protoClient: protoClient,
	}
}

// CreateTodo (mutation) create a new todo
func (client Client) CreateTodo(
	ctx context.Context,
	input NewTodo,
	fields TodoFields,
) (Todo, error) {
	var s []string
	for _, field := range fields {
		s = append(s, field.TodoFieldGraphQL())
	}
	fieldsContent := fmt.Sprintf(" { %s }", strings.Join(s, ","))

	body := graphqlclientgen.Body{
		Query: fmt.Sprintf(`
        mutation ($input: NewTodo!) {
            createTodo (input: $input)%s
        }`, fieldsContent),
		Variables: map[string]any{
			"input": input,
		},
	}

	var res graphqlclientgen.Response
	if err := client.protoClient.Do(ctx, body, &res); err != nil {
		return Todo{}, err
	}

	var data struct {
		CreateTodo Todo `json:"createTodo"`
	}

	if res.Errors != nil {
		return data.CreateTodo, *res.Errors
	}

	if err := json.Unmarshal(res.Data, &data); err != nil {
		return data.CreateTodo, err
	}

	return data.CreateTodo, nil
}

// Todo (query) get todo
func (client Client) Todo(
	ctx context.Context,
	id string,
	fields TodoFields,
) (Todo, error) {
	var s []string
	for _, field := range fields {
		s = append(s, field.TodoFieldGraphQL())
	}
	fieldsContent := fmt.Sprintf(" { %s }", strings.Join(s, ","))

	body := graphqlclientgen.Body{
		Query: fmt.Sprintf(`
        query ($id: ID!) {
            todo (id: $id)%s
        }`, fieldsContent),
		Variables: map[string]any{
			"id": id,
		},
	}

	var res graphqlclientgen.Response
	if err := client.protoClient.Do(ctx, body, &res); err != nil {
		return Todo{}, err
	}

	var data struct {
		Todo Todo `json:"todo"`
	}

	if res.Errors != nil {
		return data.Todo, *res.Errors
	}

	if err := json.Unmarshal(res.Data, &data); err != nil {
		return data.Todo, err
	}

	return data.Todo, nil
}

// Todos (query) get all todos
func (client Client) Todos(
	ctx context.Context,
	fields TodoFields,
) ([]Todo, error) {
	var s []string
	for _, field := range fields {
		s = append(s, field.TodoFieldGraphQL())
	}
	fieldsContent := fmt.Sprintf(" { %s }", strings.Join(s, ","))

	body := graphqlclientgen.Body{
		Query: fmt.Sprintf(`
        query {
            todos%s
        }`, fieldsContent),
		Variables: map[string]any{},
	}

	var res graphqlclientgen.Response
	if err := client.protoClient.Do(ctx, body, &res); err != nil {
		return nil, err
	}

	var data struct {
		Todos []Todo `json:"todos"`
	}

	if res.Errors != nil {
		return data.Todos, *res.Errors
	}

	if err := json.Unmarshal(res.Data, &data); err != nil {
		return data.Todos, err
	}

	return data.Todos, nil
}

// User (query)
func (client Client) User(
	ctx context.Context,
	id uuid.UUID,
	fields UserFields,
) (User, error) {
	var s []string
	for _, field := range fields {
		s = append(s, field.UserFieldGraphQL())
	}
	fieldsContent := fmt.Sprintf(" { %s }", strings.Join(s, ","))

	body := graphqlclientgen.Body{
		Query: fmt.Sprintf(`
        query ($id: UUID!) {
            user (id: $id)%s
        }`, fieldsContent),
		Variables: map[string]any{
			"id": id,
		},
	}

	var res graphqlclientgen.Response
	if err := client.protoClient.Do(ctx, body, &res); err != nil {
		return User{}, err
	}

	var data struct {
		User User `json:"user"`
	}

	if res.Errors != nil {
		return data.User, *res.Errors
	}

	if err := json.Unmarshal(res.Data, &data); err != nil {
		return data.User, err
	}

	return data.User, nil
}

// Users (query)
func (client Client) Users(
	ctx context.Context,
	fields UserFields,
) ([]User, error) {
	var s []string
	for _, field := range fields {
		s = append(s, field.UserFieldGraphQL())
	}
	fieldsContent := fmt.Sprintf(" { %s }", strings.Join(s, ","))

	body := graphqlclientgen.Body{
		Query: fmt.Sprintf(`
        query {
            users%s
        }`, fieldsContent),
		Variables: map[string]any{},
	}

	var res graphqlclientgen.Response
	if err := client.protoClient.Do(ctx, body, &res); err != nil {
		return nil, err
	}

	var data struct {
		Users []User `json:"users"`
	}

	if res.Errors != nil {
		return data.Users, *res.Errors
	}

	if err := json.Unmarshal(res.Data, &data); err != nil {
		return data.Users, err
	}

	return data.Users, nil
}
