---
name: Golang
on:
  push: { branches: [main] }
  pull_request:

env:
  GO_VERSION: "^1.23.1"

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - run: diff -u <(echo -n) <(gofmt -l ./)

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - run: go test -v ./...
